### ISSUE TITLE
Update supported versions for 5.1/5.2

### ISSUE THREAD

**Issue by AFaust** [xenit-eu/dynamic-extensions-for-alfresco#128]
I am not a user of this addon but since many people keep referring to it I find it is advisable to keep its "Supported Versions" section up-to-date with the most recent major releases of Alfresco so users know if they can expect it to work properly or may have to live with some hiccups.

**Comment by laurentvdl** [comment]
DE is not systematically tested against every latest release of Alfresco.
(I personally have not used Alfresco 5.1 or greater nor do I have access to enterprise editions)

Most Alfresco releases have been stable enough to not need any changes to the addon.

Users are best placed to determine if compatibility issues exist and send in a PR or issue to update the list of supported versions.

**Comment by kerkhofsd** [comment]
Hi @AFaust ,
In the current master branch we introduced integration tests for DE on different Alfresco versions. The test suite is basic and will / can be extended over time but is a good starting point.
#228 changes the 'supported Alfresco versions' in the README to the versions that are actually integration tested. 

Given the introduction of the integration testing suite and updating the supported Alfresco versions accordingly:
do you agree that this issue can be closed?

**Comment by AFaust** [comment]
I am perfectly fine with this issue being closed given the suite and updated list of supported versions.
