### ISSUE TITLE
Dot in Request parameter string

### ISSUE THREAD

**Issue by Jasper-Hilven** [xenit-eu/dynamic-extensions-for-alfresco#131]
@stanmine @laurentvdl 
Trying to put a regex with a dot for an URI tag. e.g.
@Uri(value = "/properties/{qname:.+}", method = HttpMethod.GET,formatStyle = FormatStyle.ARGUMENT)

This fails. 
I made an extra test (which fails) for this issue:

https://github.com/Jasper-Hilven/dynamic-extensions-for-alfresco on the master branch

Kind regards

**Comment by tgeens** [comment]
@Jasper-Hilven you're missing a few steps in your explanation ?

The original issue is: a dot in a `@RequestParam String arg` gets truncated at the `.`

Example: passing `foo.bar` gets truncated too `foo`
@Jasper-Hilven  Do you have a unit test that shows that issue ?

**Comment by Jasper-Hilven** [comment]
@stanmine @laurentvdl @tgeens 
Indeed that was the original issue, The regex that was already a first workaround when looking to http://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated

So the original problem was that passing /myscript/foo.bar gets truncated to /myscript/foo

Kind regards

**Comment by tgeens** [comment]
Note: this is not related to the special characters like `{` or `}`

GET https://jasperh50.dev.xenit.eu/alfresco/s/somethingwitha/dot.something.more
Expected: `dot.something.more`
Actual: `dot`

**Comment by laurentvdl** [comment]
Quick feedback,  as DE simply forwards the metadata from your annotations to the Alfresco Uri registry, did you try to achieve the same using a regular webscript?  (no DE)

**Comment by kerkhofsd** [comment]
This can be solved by using `formatStyle = FormatStyle.ARGUMENT`.
E.g. `@Uri(value = "/handleUriVariableWithFormatStyleArgument/{variable}", formatStyle = FormatStyle.ARGUMENT)`

By default, the `ANY` format style is used. This means, when the parameter is at the end of the uri, anything behind the dot will be processed as the extension and removed from the parameter.
