### ISSUE TITLE
@ResponseBody with void return type causes NullpointerException

### ISSUE THREAD

**Issue by kerkhofsd** [xenit-eu/dynamic-extensions-for-alfresco#151]
In the latest SNAPSHOT builds, `@ResponseBody` was introduced.

Using the `@ResponseBody` together with a void return type, causes a NullPointerException in the AnnotationWebscript class.

**Comment by stanmine** [comment]
Hello @kerkhofsd,

I was able to reproduce this issue. I will create a fix a soon as possible.
