### ISSUE TITLE
Autowired beans null in RepositoryModelRegistrar

### ISSUE THREAD

**Issue by TheElvenPath** [xenit-eu/dynamic-extensions-for-alfresco#164]
Hello. If i add spring context with at least one bean to resources/META-INF/spring/module-context.xml than not loading model from META-INF/alfresco/models because of NullPointerException in com.github.dynamicextensionsalfresco.models.RepositoryModelRegistrar - all @autowired beans are null. If i remove xml configuration all works fine. Is any possible opportunity to use both - xml and annotation configuration?

**Comment by laurentvdl** [comment]
Hi, you can import Spring xml from a `@Configuration` bean.
Checkout the article at https://www.mkyong.com/spring/spring-mixing-xml-and-javaconfig/: Load Spring XML From JavaConfig.

This means, in this case, you should not store your Spring xml in META-INF, as this disables classpath scanning in your extension.

```java
@Configuration
@ImportResource("classpath:/external-spring-config.xml")
public class ExternalConfiguration {}
```

**Comment by TheElvenPath** [comment]
Hi, it worked for me, but with another problem. 
Now when setting up bean in xml context (xml is legacy repo module context) 
```xml
<bean id="someID">
<property name="entityType" value="letters:income" />
</bean>
```
always fails to load with error:
```
Caused by: java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.alfresco.service.namespace.QName] for property 'entityType': no matching editors or conversion strategy found
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:267)
```

registering custom property registrar is not help

```xml
	<bean class="org.springframework.beans.factory.config.CustomEditorConfigurer">
		<property name="propertyEditorRegistrars">
			<list>
				<ref bean="customPropertyEditorRegistrar"/>
			</list>
		</property>
	</bean>

	<bean id="customPropertyEditorRegistrar"
		  class="org.alfresco.util.CustomPropertyEditorRegistrar">
		<property name="namespaceService" ref="NamespaceService"/>
	</bean>
```
And from Java configuration too.

**Comment by yregaieg** [comment]
Please create different tickets for different questions.
The problem you stated is not related to dynamic extensions, please follow up on it on community.alfresco.com

**Comment by TheElvenPath** [comment]
@yregaieg But it works on alfresco. It not working only if install taht module like bundle and import module spring context. In debugger that editor in alfresco application context, and is not in osgi application context.

**Comment by laurentvdl** [comment]
@TheElvenPath 
The Editor approach is what I would have tried as well.

As a last resort, you can deploy your legacy .xml as a regular Alfresco extension.
If you need interop with a dynamic extension service, you can use https://github.com/xenit-eu/dynamic-extensions-for-alfresco/wiki/Service-proxies.
