### ISSUE TITLE
Use compileOnly dependencies in the gradle plugin

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/dynamic-extensions-for-alfresco#180]
## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior

When building a new dynamic extension with the gradle plugin, only runtime dependencies that are not already bundled with Alfresco are present in the default configuration.

## Current Behavior

The dependencies added by the dynamic extensions plugin (spring components, DE annotations) are present in the default configuration, which leads to them being pulled in in a parent project that uses the DE project directly as a dependency.

## Possible Solution

Compile dependencies get pulled in and bundled in the compiled jar, but these dependencies are already provided by dynamic extensions, so they should not be bundled.
Currently, we use transitive = false everywhere to avoid bundling all these jars, but compileOnly dependencies are a better option, because then they are not included in the runtime dependencies

## Context

```gradle
// subproject/build.gradle
buildscript {
  repositories { 
    jcenter()
  }
  dependencies {
    classpath(group: 'eu.xenit.de', name: 'gradle-plugin', version: '1.7.+')
  }
}

repositories { 
    jcenter()
}

apply plugin: 'alfresco-dynamic-extension'
apply plugin: 'idea'
apply plugin: 'java'

task dumpDefaultConfiguration {
    doFirst {
        configurations.default
                .files.each { file -> println "\n" + file}
    }
}
```

```gradle
// build.gradle
configurations{
   alfrescoDE
}
dependencies {
   // ....
   alfrescoDE project(path: 'subproject')
}

task dumpDEConfiguration {
    doFirst {
        configurations.alfrescoDE
                .files.each { file -> println "\n" + file}
    }
}
```

Dumping all the dependent files of the parent project with `./gradlew :dumpDEConfiguration` shows that a lot of compiletime dependencies are pulled in that are already available on the classpath when Alfresco and the Dynamic Extensions amp are installed.

**Comment by stanmine** [comment]
PR merged in
