### ISSUE TITLE
How the internals is working by which class the plugin is started

### ISSUE THREAD

**Issue by gdeverlant** [xenit-eu/dynamic-extensions-for-alfresco#244]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report
[ ] feature request
[x ] question
```
1. I would like to know which class should I put a breakpoint in to debug DE? I would like to know which class is first instanciated by spring when Alfresco is starting and registering this plugin.
2. Is there a way to debug DE inside of Eclipse IDE while running Tomcat  in Debug mode?
3. How to setup my eclipse environment to debug this AMP in Tomcat and contribute to it?

**Comment by gdeverlant** [comment]
I was able to come up to this debug phase but somehow it is not possible to get eclipse recognize the FrameworkManager.java class from the FameworkManager.kt file.

![screenshot](https://pasteboard.co/Ieeyo0cr.png)

**Comment by gdeverlant** [comment]
After installing the 2.0.0 version of DE it seems that there is nothing related with Kotlin anymore. The standard class debugging is working like a charm now. I really don't understand why that DefaultFrameworkManager.kt file appeared from nowhere.

![image](https://user-images.githubusercontent.com/26530975/57591149-418ab480-7530-11e9-8685-5f084ae90b61.png)

**Comment by kerkhofsd** [comment]
Hi @gdeverlant ,
FYI: In the current master, DE version 2.0.0, we converted all Kotlin classes to Java to simplify the project. 

Do you have all the information you need?

**Comment by gdeverlant** [comment]
I would say that this is the best move that you guys did! Removing the Kotlin related stuff helped a lot for me to debug step by step all the internal code so that I can understand it.

Kudos !!!!

**Comment by kerkhofsd** [comment]
Thanks, great to hear!
