### ISSUE TITLE
Gradle says Lambdas aren't supported after applying plugin

### ISSUE THREAD

**Issue by rschev** [xenit-eu/dynamic-extensions-for-alfresco#265]
## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior
The gradle build succeeds without warnings or errors.

## Current Behavior
I see the following lines during the `jar` step:
> \> Task :c4a-test:test-6x:jar
>Task ':c4a-test:test-6x:jar' is not up-to-date because:
>  Additional action for task ':c4a-test:test-6x:jar': was implemented by the Java lambda 'com.github.dynamicextensionsalfresco.gradle.tasks.DeBundleTaskConvention$$Lambda$122/640236900'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
>Custom actions are attached to task ':c4a-test:test-6x:jar'.

## Possible Solution
There's only one lambda in DeBundleTaskConvention.java. Replace the line
```java
        task.doLast("buildDeBundle", t -> buildDeBundle());
```
with
```java
        task.doLast("buildDeBundle", new Action<Task>() {
            @Override
            public void execute(Task task) {
                buildDeBundle();
            }
        });
```

## Steps to Reproduce (for bugs)

1. Checkout care4alf branch ALFREDOPS-261-2
2. `./gradlew clean :c4a-test:test-6x:integrationTest --info --stacktrace`
I can't get it any more specific than that, it's not clear to me what part of the build causes this. `./gradlew :c4a-test:test-6x:jar` by itself doesn't cause the problem.

## Context
Despite the message implicating that part of the code isn't supported, my build seems to work fine. It might just be the up-to-date check that is bothered by this.

## Your Environment

* Alfresco version used: 6.0, but I don't think it matters.
* DE version used: 2.0.1

**Comment by kerkhofsd** [comment]
Seems related: https://github.com/gradle/gradle/issues/5510
