### ISSUE TITLE
Configuration scheduled jobs cron value in properties file

### ISSUE THREAD

**Issue by mkczyk** [xenit-eu/dynamic-extensions-for-alfresco#277]
I would like to externalize cron expression in [scheduled jobs](https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/master/documentation/Extension_Point_Scheduled_Jobs.md) to `alfresco-global.properties` file for changing value without modifying code. For example for administrator configuration.

## I'm submitting a...
```
[ ] bug report
[x] feature request
[x] question
```

## Expected Behavior

Java class:

    @ScheduledTask(name = "example", cron = "my-extension-name.my-job-name.cron")

And line in alfresco-global.properties file:

    my-extension-name.my-job-name.cron=0/15 * * * * ?

## Current Behavior

I can write cron value once and have to recompile and redeploy to change value:

    @ScheduledTask(name = "example", cron = "0/15 * * * * ?")

## Possible Solution

I think implementation of this feature isn't very simple. For example Feign have the same problem:
- https://stackoverflow.com/questions/29278005/can-i-configure-a-feignclient-url-using-a-properties-yml-file
- https://stackoverflow.com/questions/43733569/how-can-i-change-the-feign-url-during-the-runtime

## Context

Without this feature deploying scheduled jobs on production is limited. Administrator can't disable scheduled job without installing AMP.

**Comment by vierbergenlars** [comment]
Hello @mkczyk,

The `@ScheduledTask` annotation has a field `cronProp` that can be used for this purpose: https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/master/annotations/src/main/java/com/github/dynamicextensionsalfresco/schedule/ScheduledTask.java#L45
However, it does not appear to be in the documentation, so we should probably take a look at that.
