### ISSUE TITLE
Dynamic Extensions not starting with Spring 3 and no internet

### ISSUE THREAD

**Issue by todorinskiz** [xenit-eu/dynamic-extensions-for-alfresco#287]
## I'm submitting a ...   (check one with "x")
```
[X] bug report
[ ] feature request
[ ] question
```

## Caused By

- https://github.com/xenit-eu/dynamic-extensions-for-alfresco/issues/267
- https://github.com/xenit-eu/dynamic-extensions-for-alfresco/issues/268

## Possible Solution

1. Add local xsd resources and reference them with `classpath:` annotation instead of with `spring.schemas`

## Steps to Reproduce (for bugs)

1. Deploy Dynamic Extensions 2.0.2 on Alfresco 5.x
2. Alfresco bootstrap will fail

## Your Environment

* Alfresco version used: Alfresco 5.x
* DE version used: Dynamic Extensions 2.0.2

**Comment by kerkhofsd** [comment]
Fixed by #288
