### ISSUE TITLE
Fix confusing Event.ALL Behaviour notification time

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/dynamic-extensions-for-alfresco#295]
The name of the time that the behaviour is called is confusing in the case of `ALL`.

The explanation here seems to indicate that the behaviour is multiple times when using `Event.ALL`.

This is scary, because you never want behaviour code to be called multiple times, leading to developers using the "next best thing" of `Event.COMMIT`, when in fact `Event.ALL` is usually the best choice.

https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/f4039c0615a7d7c66153eff4a38a9a0f910b3255/annotations/src/main/java/com/github/dynamicextensionsalfresco/behaviours/annotations/Event.java#L19-L25

However, the [Alfresco documentation](https://docs.alfresco.com/5.2/references/dev-extension-points-behaviors.html) states that:

> It is possible to do even more fine-tuning of where in the transaction event handlers should be called (that is, compared to just before or after an operation). There are three different stages (Alfresco Content Services calls it notification frequencies) where the custom handler could be configured to be invoked:
>
> * `EVERY_EVENT`: This is the default if the notification frequency is not specified. The event handler is then just executed wherever it is being invoked in the code. The name of this notification frequency implies that the event handler will be called multiple times, but that is not the case.
> * `TRANSACTION_COMMIT`: The event handler is queued and invoked at the end of the transaction after it has been committed. A proxy around the event handler manages the queuing.
> * `FIRST_EVENT`: The event handler is invoked just after the transaction is started. A proxy around the event handler manages this.
>
> > *Important:* When using the event manager it is important to know that it manages synchronous events. So whatever code we implement in the event handler will be executed in the same transaction as the main Alfresco Content Services code that triggered the event. This means that the code in the event handler will impact the performance of general Alfresco Content Services operations such as adding a document. So we need to be careful about this and use this event system only when it is really necessary.

`Event.ALL` maps to `EVERY_EVENT`, which, per the Alfresco documentation, results in the behaviour only being called once, and it being called synchronously.

## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior

I expect the name of the `EVERY_EVENT` notification time behaviour to be more clear in indicating that the behaviour will called synchronously, when the Alfresco core code invokes the behaviour.

## Current Behavior

The name `Event.ALL` sounds scary and confuses developers into thinking the behaviour will be called multiple times.

## Possible Solution

1. At least update the documentation of `Event.ALL` to state this issue
2. Preferrably rename `Event.ALL` to `Event.SYNCHRONOUS` (or something similar)
    This can be done without breaking backwards compatibility by temporarily having both values and handling them in the same way. `Event.ALL` should be marked `@Deprecated`

**Comment by tgeens** [comment]
`EVERY_EVENT` also means if you update 50 properties on a node, your behavior gets invoked 50 times.

**Comment by kerkhofsd** [comment]
https://docs.alfresco.com/content-services/6.1/develop/repo-ext-points/behavior-policies/

Alfresco documentation got an update:

> EVERY_EVENT: This is the default if the notification frequency is not specified. The event handler is then just executed wherever it is being invoked in the code. The name of this notification frequency implies that the event handler will be called multiple times, which is true. The EVERY_EVENT notification frequency can be called numerous times within a single transaction (a lot more than you might expect), so unless your behavior logic is fast+in-repository-only (no RPCs, no external data access, etc.) or asynchronous, it’s easy to seriously impact Alfresco’s performance. It’s recommended to implement “early check and bail out” when this notification frequency is used, e.g. checking the affected store and actual change (if a property value has actually been modified or the correct aspect been applied). If this is done, then there is very limited chance of a noticeable performance penalty.

So as @tgeens already mentioned the code actually is called multiple times. Therefore, `Event.ALL` is not a bad name after all? 

This part of the Javadoc doesn't look right though:
> In practice, this means the Behaviour is triggered at the start and at the commit. (I.e. the start and transaction commit are the only events.) 

In conclusion, the action to take is here is to update the Javadoc for the `Event.ALL()`, do I understand correctly @vierbergenlars ?

**Comment by vierbergenlars** [comment]
Yes, the javadoc is just plain wrong, which I think contributed to my confusion.

With `EVERY_EVENT` notification frequency, it's not called at start and at commit, only *once*, at the time the event effectively occurs (before transaction commit)

**Comment by kerkhofsd** [comment]
@vierbergenlars If I'm not mistaking, with `EVERY_EVENT` (/ `Events.ALL()`) the behavior is triggered each time and immediately after the relevant event occurs. (So not necessarily once and not before transaction commit...).
