### ISSUE TITLE
Extend documentation of the ScheduledTask annotation

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/dynamic-extensions-for-alfresco#314]
## I'm submitting a ...   (check one with "x")
```
[ ] bug report
[X] feature request
[ ] question
```

## Expected Behavior
The `cluster` property on the `ScheduledTask` annotation is properly documented

## Current Behavior
The cluster property is only explained in the javadoc.

## Possible Solution
Add section to the documentation md-file.

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A

**Comment by kerkhofsd** [comment]
Closed via #315
