### ISSUE TITLE
Exception handler not working

### ISSUE THREAD

**Issue by katyaterletskaya** [xenit-eu/dynamic-extensions-for-alfresco#319]
According to the documentation (https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/master/documentation/Extension_Point_WebScripts.md) I can _separate out exception handler methods into their own class, using an interface with default methods. The interface can then be implemented by any @WebScript class that requires it_, but it does not work

## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior
I expect to see `400 Bad Request`

## Current Behavior
`The Web Script <a href="%2Ftest">/test</a> has responded with a status of 500 - Internal Error.`

## Possible Solution
I tried using `class` instead of `interface` and it works.

## Steps to Reproduce (for bugs)
1. Create a global exception handler
```
public interface ExceptionHandlers {
  @ExceptionHandler(IllegalArgumentException.class)
  default void handleIllegalArgument(IllegalArgumentException exception, WebScriptResponse response) {
    response.setStatus(400);
  }
}
```
2. Create webscript with endpoint that throws an exception
```
@Component
@WebScript
public class TestWebScript implements ExceptionHandlers {

  @ResponseBody
  @Uri(value = "/test")
  public void test() {
    throw new IllegalArgumentException();
  }
}
```
3. Make an api call

## Your Environment
* Alfresco version used: 5.2.7.2
* DE version used: 2.0.5

**Comment by kerkhofsd** [comment]
Hi @katyaterletskaya , thanks for the bug report. 

I added some integration tests, which indeed fail because the `@ExceptionHandler` annotated method is not triggered:
https://github.com/xenit-eu/dynamic-extensions-for-alfresco/commit/afa5c03ec8539d200d0f7894b51f6618d3cae1ab

Strangely, I thought this approach was already used by our team before. I'll ask around and investigate why it might have worked. 

We certainly need to fix this, either in the documentation or in the implementation. 
Would it be possible to use an abstract class as a (temporary) workaround?

**Comment by katyaterletskaya** [comment]
Hi @kerkhofsd , thanks for the answer, I'll use abstract class as a workaround 👍🏻

I also have a question regarding exception handlers. I was thinking about options for handling the exception thrown by [RequestBodyArgumentResolver](https://github.com/xenit-eu/dynamic-extensions-for-alfresco/blob/master/annotations-runtime/src/main/java/com/github/dynamicextensionsalfresco/webscripts/arguments/RequestBodyArgumentResolver.java), but I was only able to add an exception handler for RuntimeException. Is there any other option for this? This exception handler will handle all types of exceptions.

**Comment by kerkhofsd** [comment]
After some investigation, we discovered that using the `@ExceptionHandler` annotation on `default` interface methods does work for Alfresco >= 6 (Spring >= 5). 

We internally use Spring's `ReflectionUtils` to register the methods. That class does not yet scan default interface methods in the Spring versions used by Alfresco <= 5. For information, the [relevant commit](https://github.com/spring-projects/spring-framework/commit/192462902ef3d97c0b6684d467c7d2023ecd5be1) in the Spring Framework. 

We'll add a disclaimer in the projects documentation that indicates this can only be used with Alfresco >= 6. 
As already mentioned, exception handling methods can be registered in all Alfresco versions using reusable abstract classes. 

Full credit to @tgeens for pinpointing the problem and explanation.

**Comment by kerkhofsd** [comment]
> I also have a question regarding exception handlers. Can I have my own handler for all unexpected exceptions (for example add an exception handler for RuntimeException / Throwable)? I tried this, but this handler will handle all types of exceptions.

I don't know if I fully understand the question. Do you mean to add an additional exception handler that is only triggered if the exception is not yet handled by any `@ExceptionHandler`?

**Comment by katyaterletskaya** [comment]
> I don't know if I fully understand the question. Do you mean to add an additional exception handler that is only triggered if the exception is not yet handled by any `@ExceptionHandler`?

yes, I want to have a handler for the cases where there is no handler for specific exception 🙂

**Comment by kerkhofsd** [comment]
I'm afraid that's currently not possible. 
I would advise to include a generic `@ExceptionHandler` and manually orchestrate delegation to different methods based on e.g. the type of the exception.
