### ISSUE TITLE
Support for Alfresco 7.0 Enterprise Version

### ISSUE THREAD

**Issue by am-tribia** [xenit-eu/dynamic-extensions-for-alfresco#322]
Hi,

Alfresco has released ACS 7.0 yesterday and would like to know if there are any plans to support it. Also would like to know 
how good the https://github.com/Alfresco/alfresco-extension-inspector works when we have extended using dynamic-extensions-for-alfresco.

Cheers

Ayyanar.M

**Comment by kerkhofsd** [comment]
Hi @am-tribia ,

Although we will certainly support ACS 7.0, we did not yet pinpoint a target date for this. 
If you are eager to use Dynamic Extensions on Alfresco 7 we are happy to collaborate on any contribution. In theory we can already build the necessary (-SNAPSHOT) artifacts. However for integration testing we rely on our docker stack, for which the 7.0 versions have yet to be created. 

I only had a quick look at the `alfresco-extension-inspector` so far. 
However I'm quite convinced DE bundles cannot be analysed by the tool given that:
- DE bundles are installed in a special, dedicated location
- the layout of DE bundles differs from standard Alfresco jars.

Kind regards,
Daan
