### ISSUE TITLE
Dynamic extensions gradle plugin was not published

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/dynamic-extensions-for-alfresco#329]
## I'm submitting a ...   (check one with "x")
```
[x] bug report
[ ] feature request
[ ] question
```

## Expected Behavior

A gradle plugin `eu.xenit.de` is published with the same version as dynamic extensions itself

## Current Behavior

Missing version `2.1.0` for the Gradle plugin

## Possible Solution

Update the release process to also call the `publishPlugins` task

## Steps to Reproduce (for bugs)

1. Look at https://plugins.gradle.org/plugin/eu.xenit.de
2. See that no version 2.1.0 has been published.

## Your Environment

* Alfresco version used:
* DE version used:

**Comment by kerkhofsd** [comment]
My bad, missed this in PR #327
