### ISSUE TITLE
Support Alfresco Versions > 7.0.x

### ISSUE THREAD

**Issue by siemensoe** [xenit-eu/dynamic-extensions-for-alfresco#345]

**Comment by todorinskiz** [comment]
Hi @siemensoe ,

With the latest release Alfresco 7.0 up to 7.2 are also supported.
https://github.com/xenit-eu/dynamic-extensions-for-alfresco/pull/349

Enjoy and let us know if you encounter any issues with this release.

Kind regards,
Zlatin
